// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "UpdateConfig.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>

namespace AANF_Protocol {

namespace {

const ::google::protobuf::Descriptor* UpdateConfigRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UpdateConfigRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* UpdateConfigResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UpdateConfigResponse_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* UpdateConfigResponse_ErrorCode_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_UpdateConfig_2eproto() {
  protobuf_AddDesc_UpdateConfig_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "UpdateConfig.proto");
  GOOGLE_CHECK(file != NULL);
  UpdateConfigRequest_descriptor_ = file->message_type(0);
  static const int UpdateConfigRequest_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateConfigRequest, md5_),
  };
  UpdateConfigRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      UpdateConfigRequest_descriptor_,
      UpdateConfigRequest::default_instance_,
      UpdateConfigRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateConfigRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateConfigRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(UpdateConfigRequest));
  UpdateConfigResponse_descriptor_ = file->message_type(1);
  static const int UpdateConfigResponse_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateConfigResponse, error_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateConfigResponse, md5_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateConfigResponse, config_content_),
  };
  UpdateConfigResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      UpdateConfigResponse_descriptor_,
      UpdateConfigResponse::default_instance_,
      UpdateConfigResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateConfigResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateConfigResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(UpdateConfigResponse));
  UpdateConfigResponse_ErrorCode_descriptor_ = UpdateConfigResponse_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_UpdateConfig_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    UpdateConfigRequest_descriptor_, &UpdateConfigRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    UpdateConfigResponse_descriptor_, &UpdateConfigResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_UpdateConfig_2eproto() {
  delete UpdateConfigRequest::default_instance_;
  delete UpdateConfigRequest_reflection_;
  delete UpdateConfigResponse::default_instance_;
  delete UpdateConfigResponse_reflection_;
}

void protobuf_AddDesc_UpdateConfig_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::Protocol::protobuf_AddDesc_PacketFormat_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022UpdateConfig.proto\022\rAANF_Protocol\032\022Pac"
    "ketFormat.proto\"\"\n\023UpdateConfigRequest\022\013"
    "\n\003md5\030\004 \002(\t\"\242\001\n\024UpdateConfigResponse\022<\n\005"
    "error\030\004 \002(\0162-.AANF_Protocol.UpdateConfig"
    "Response.ErrorCode\022\013\n\003md5\030\005 \002(\t\022\026\n\016confi"
    "g_content\030\006 \002(\t\"\'\n\tErrorCode\022\r\n\tNO_UPDAT"
    "E\020\000\022\013\n\007UPDATED\020\001:U\n\021update_config_req\022\026."
    "Protocol.PacketFormat\030e \001(\0132\".AANF_Proto"
    "col.UpdateConfigRequest:V\n\021update_config"
    "_rsp\022\026.Protocol.PacketFormat\030f \001(\0132#.AAN"
    "F_Protocol.UpdateConfigResponse", 431);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "UpdateConfig.proto", &protobuf_RegisterTypes);
  UpdateConfigRequest::default_instance_ = new UpdateConfigRequest();
  UpdateConfigResponse::default_instance_ = new UpdateConfigResponse();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::Protocol::PacketFormat::default_instance(),
    101, 11, false, false,
    &::AANF_Protocol::UpdateConfigRequest::default_instance());
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::Protocol::PacketFormat::default_instance(),
    102, 11, false, false,
    &::AANF_Protocol::UpdateConfigResponse::default_instance());
  UpdateConfigRequest::default_instance_->InitAsDefaultInstance();
  UpdateConfigResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_UpdateConfig_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_UpdateConfig_2eproto {
  StaticDescriptorInitializer_UpdateConfig_2eproto() {
    protobuf_AddDesc_UpdateConfig_2eproto();
  }
} static_descriptor_initializer_UpdateConfig_2eproto_;


// ===================================================================

const ::std::string UpdateConfigRequest::_default_md5_;
#ifndef _MSC_VER
const int UpdateConfigRequest::kMd5FieldNumber;
#endif  // !_MSC_VER

UpdateConfigRequest::UpdateConfigRequest() {
  SharedCtor();
}

void UpdateConfigRequest::InitAsDefaultInstance() {
}

UpdateConfigRequest::UpdateConfigRequest(const UpdateConfigRequest& from) {
  SharedCtor();
  MergeFrom(from);
}

void UpdateConfigRequest::SharedCtor() {
  _cached_size_ = 0;
  md5_ = const_cast< ::std::string*>(&_default_md5_);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

UpdateConfigRequest::~UpdateConfigRequest() {
  SharedDtor();
}

void UpdateConfigRequest::SharedDtor() {
  if (md5_ != &_default_md5_) {
    delete md5_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* UpdateConfigRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UpdateConfigRequest_descriptor_;
}

const UpdateConfigRequest& UpdateConfigRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_UpdateConfig_2eproto();  return *default_instance_;
}

UpdateConfigRequest* UpdateConfigRequest::default_instance_ = NULL;

UpdateConfigRequest* UpdateConfigRequest::New() const {
  return new UpdateConfigRequest;
}

void UpdateConfigRequest::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (_has_bit(0)) {
      if (md5_ != &_default_md5_) {
        md5_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool UpdateConfigRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string md5 = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) !=
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          goto handle_uninterpreted;
        }
        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
              input, this->mutable_md5()));
        ::google::protobuf::internal::WireFormat::VerifyUTF8String(
          this->md5().data(), this->md5().length(),
          ::google::protobuf::internal::WireFormat::PARSE);
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void UpdateConfigRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  ::google::protobuf::uint8* raw_buffer = output->GetDirectBufferForNBytesAndAdvance(_cached_size_);
  if (raw_buffer != NULL) {
    UpdateConfigRequest::SerializeWithCachedSizesToArray(raw_buffer);
    return;
  }
  
  // required string md5 = 4;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->md5().data(), this->md5().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->md5(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* UpdateConfigRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string md5 = 4;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->md5().data(), this->md5().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->md5(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int UpdateConfigRequest::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string md5 = 4;
    if (has_md5()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->md5());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  _cached_size_ = total_size;
  return total_size;
}

void UpdateConfigRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const UpdateConfigRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const UpdateConfigRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void UpdateConfigRequest::MergeFrom(const UpdateConfigRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_md5(from.md5());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void UpdateConfigRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UpdateConfigRequest::CopyFrom(const UpdateConfigRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateConfigRequest::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void UpdateConfigRequest::Swap(UpdateConfigRequest* other) {
  if (other != this) {
    std::swap(md5_, other->md5_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata UpdateConfigRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UpdateConfigRequest_descriptor_;
  metadata.reflection = UpdateConfigRequest_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* UpdateConfigResponse_ErrorCode_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UpdateConfigResponse_ErrorCode_descriptor_;
}
bool UpdateConfigResponse_ErrorCode_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const UpdateConfigResponse_ErrorCode UpdateConfigResponse::NO_UPDATE;
const UpdateConfigResponse_ErrorCode UpdateConfigResponse::UPDATED;
const UpdateConfigResponse_ErrorCode UpdateConfigResponse::ErrorCode_MIN;
const UpdateConfigResponse_ErrorCode UpdateConfigResponse::ErrorCode_MAX;
#endif  // _MSC_VER
const ::std::string UpdateConfigResponse::_default_md5_;
const ::std::string UpdateConfigResponse::_default_config_content_;
#ifndef _MSC_VER
const int UpdateConfigResponse::kErrorFieldNumber;
const int UpdateConfigResponse::kMd5FieldNumber;
const int UpdateConfigResponse::kConfigContentFieldNumber;
#endif  // !_MSC_VER

UpdateConfigResponse::UpdateConfigResponse() {
  SharedCtor();
}

void UpdateConfigResponse::InitAsDefaultInstance() {
}

UpdateConfigResponse::UpdateConfigResponse(const UpdateConfigResponse& from) {
  SharedCtor();
  MergeFrom(from);
}

void UpdateConfigResponse::SharedCtor() {
  _cached_size_ = 0;
  error_ = 0;
  md5_ = const_cast< ::std::string*>(&_default_md5_);
  config_content_ = const_cast< ::std::string*>(&_default_config_content_);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

UpdateConfigResponse::~UpdateConfigResponse() {
  SharedDtor();
}

void UpdateConfigResponse::SharedDtor() {
  if (md5_ != &_default_md5_) {
    delete md5_;
  }
  if (config_content_ != &_default_config_content_) {
    delete config_content_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* UpdateConfigResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UpdateConfigResponse_descriptor_;
}

const UpdateConfigResponse& UpdateConfigResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_UpdateConfig_2eproto();  return *default_instance_;
}

UpdateConfigResponse* UpdateConfigResponse::default_instance_ = NULL;

UpdateConfigResponse* UpdateConfigResponse::New() const {
  return new UpdateConfigResponse;
}

void UpdateConfigResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    error_ = 0;
    if (_has_bit(1)) {
      if (md5_ != &_default_md5_) {
        md5_->clear();
      }
    }
    if (_has_bit(2)) {
      if (config_content_ != &_default_config_content_) {
        config_content_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool UpdateConfigResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .AANF_Protocol.UpdateConfigResponse.ErrorCode error = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) !=
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          goto handle_uninterpreted;
        }
        int value;
        DO_(::google::protobuf::internal::WireFormatLite::ReadEnum(input, &value));
        if (::AANF_Protocol::UpdateConfigResponse_ErrorCode_IsValid(value)) {
          set_error(static_cast< ::AANF_Protocol::UpdateConfigResponse_ErrorCode >(value));
        } else {
          mutable_unknown_fields()->AddVarint(4, value);
        }
        if (input->ExpectTag(42)) goto parse_md5;
        break;
      }
      
      // required string md5 = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) !=
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          goto handle_uninterpreted;
        }
       parse_md5:
        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
              input, this->mutable_md5()));
        ::google::protobuf::internal::WireFormat::VerifyUTF8String(
          this->md5().data(), this->md5().length(),
          ::google::protobuf::internal::WireFormat::PARSE);
        if (input->ExpectTag(50)) goto parse_config_content;
        break;
      }
      
      // required string config_content = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) !=
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          goto handle_uninterpreted;
        }
       parse_config_content:
        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
              input, this->mutable_config_content()));
        ::google::protobuf::internal::WireFormat::VerifyUTF8String(
          this->config_content().data(), this->config_content().length(),
          ::google::protobuf::internal::WireFormat::PARSE);
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void UpdateConfigResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  ::google::protobuf::uint8* raw_buffer = output->GetDirectBufferForNBytesAndAdvance(_cached_size_);
  if (raw_buffer != NULL) {
    UpdateConfigResponse::SerializeWithCachedSizesToArray(raw_buffer);
    return;
  }
  
  // required .AANF_Protocol.UpdateConfigResponse.ErrorCode error = 4;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->error(), output);
  }
  
  // required string md5 = 5;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->md5().data(), this->md5().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->md5(), output);
  }
  
  // required string config_content = 6;
  if (_has_bit(2)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->config_content().data(), this->config_content().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->config_content(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* UpdateConfigResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .AANF_Protocol.UpdateConfigResponse.ErrorCode error = 4;
  if (_has_bit(0)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->error(), target);
  }
  
  // required string md5 = 5;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->md5().data(), this->md5().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->md5(), target);
  }
  
  // required string config_content = 6;
  if (_has_bit(2)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->config_content().data(), this->config_content().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->config_content(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int UpdateConfigResponse::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .AANF_Protocol.UpdateConfigResponse.ErrorCode error = 4;
    if (has_error()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->error());
    }
    
    // required string md5 = 5;
    if (has_md5()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->md5());
    }
    
    // required string config_content = 6;
    if (has_config_content()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->config_content());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  _cached_size_ = total_size;
  return total_size;
}

void UpdateConfigResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const UpdateConfigResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const UpdateConfigResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void UpdateConfigResponse::MergeFrom(const UpdateConfigResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_error(from.error());
    }
    if (from._has_bit(1)) {
      set_md5(from.md5());
    }
    if (from._has_bit(2)) {
      set_config_content(from.config_content());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void UpdateConfigResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UpdateConfigResponse::CopyFrom(const UpdateConfigResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateConfigResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  
  return true;
}

void UpdateConfigResponse::Swap(UpdateConfigResponse* other) {
  if (other != this) {
    std::swap(error_, other->error_);
    std::swap(md5_, other->md5_);
    std::swap(config_content_, other->config_content_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata UpdateConfigResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UpdateConfigResponse_descriptor_;
  metadata.reflection = UpdateConfigResponse_reflection_;
  return metadata;
}

::google::protobuf::internal::ExtensionIdentifier< ::Protocol::PacketFormat,
    ::google::protobuf::internal::MessageTypeTraits< ::AANF_Protocol::UpdateConfigRequest >, 11, false >
  update_config_req(kUpdateConfigReqFieldNumber, ::AANF_Protocol::UpdateConfigRequest::default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::Protocol::PacketFormat,
    ::google::protobuf::internal::MessageTypeTraits< ::AANF_Protocol::UpdateConfigResponse >, 11, false >
  update_config_rsp(kUpdateConfigRspFieldNumber, ::AANF_Protocol::UpdateConfigResponse::default_instance());

}  // namespace AANF_Protocol
